# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('title_az', models.CharField(max_length=120, null=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_az', models.TextField(null=True)),
            ],
        ),
    ]
